### ISSUE TITLE
"npm start" fails

### ISSUE THREAD

**Issue by chexbox** [s3blocks/s3blocks#15]
```> s3blocks@4.3.0 start /home/pi/s3blocks
> beefy browser.js:bundle.js --live --port 8080

beefy (v2.1.8) is listening on http://127.0.0.1:8080
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/pi/s3blocks/node_modules/babel-types/lib/definitions/index.js ENOSPC
    at _errnoException (util.js:992:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/pi/s3blocks/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/pi/s3blocks/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/pi/s3blocks/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/pi/s3blocks/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/pi/s3blocks/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:153:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! s3blocks@4.3.0 start: `beefy browser.js:bundle.js --live --port 8080`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the s3blocks@4.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-08-13T23_14_03_081Z-debug.log
```
[2018-08-13T23_14_03_081Z-debug.log](https://github.com/s3blocks/s3blocks/files/2285015/2018-08-13T23_14_03_081Z-debug.log)

**Comment by ZenithRogue** [comment]
did you run npm install beforehand?

**Comment by chexbox** [comment]
Yes. I finally got `npm install` to work:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

audited 9719 packages in 37.538s
found 2 vulnerabilities (1 moderate, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```
